.open BOOKSTORE.db

-- USER INSERTS
INSERT INTO USER VALUES();

-- LISTING INSERTS
INSERT INTO LISTING VALUES();

-- BOOK INSERTS
INSERT INTO BOOK VALUES();

-- USER_REVIEW INSERTS
INSERT INTO USER_REVIEW VALUES();

-- BOOK_REVIEW INSERTS
INSERT INTO BOOK_REVIEW VALUES();

-- TRANSACTION INSERTS
INSERT INTO TRANSACTION VALUES();